# Generated by Django 2.2.1 on 2019-05-28 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='desc',
        ),
    ]
